# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-22 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCreated',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_val', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='NoteShared',
            fields=[
                ('ns_id', models.AutoField(primary_key=True, serialize=False)),
                ('accessType', models.BooleanField(default=False)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NoteCreated')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='noteshared',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='notecreated',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
