# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-22 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteshared',
            old_name='accessType',
            new_name='s_accessType',
        ),
        migrations.RenameField(
            model_name='noteshared',
            old_name='ns_id',
            new_name='s_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='u_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='u_phone',
        ),
    ]
